# Generated by Django 6.0 on 2026-05-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_profile_company_description_profile_company_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_certificate',
            field=models.FileField(blank=True, null=True, upload_to='company_certificates/'),
        ),
    ]
